language: python
python: '3.6'

install:
  - make install
  - pip install twine

script:
  - make lint
  - make build

deploy:
  skip_cleanup: true
  provider: script
  script: make deploy
  on:
    branch: master
