language: python
python: '3.6'

install: 
  - make install
  - pip install twine

jobs:
  include:
    - stage: build
      script:
        - make lint
        - make build
    - stage: deploy
      script:
        - make deploy
