language: python
python: '3.6'

install: "make install"

jobs:
  include:
    - stage: lint
      script:
        - make lint
    - stage: build
      script:
        - make build
    - stage: deploy
      script:
        - make deploy
